import React from 'react';
import { Gantt } from '../components/gantt/gantt';
import { ViewMode, type Task } from '../types';
import { storyDebug } from '../utils/debug';

const TASKS = [
  // 硫化缸01-10
  {
    id: '硫化缸01',
    name: '硫化缸01',
    progress: 0,
    type: 'task' as const,
    hideChildren: false,
    children: [
      {
        id: 'WO-1001',
        name: 'WO-1001 - 胶料A',
        start: new Date(2024, 11, 25, 6, 0, 0).getTime(),
        end: new Date(2024, 11, 25, 7, 30, 0).getTime(),
        progress: 45,
        type: 'task' as const,
        invOrg: 'ORG-01',
        woCode: 'WO-1001',
        operation: 'OP-1',
        workCenter: '硫化缸01',
        materialCode: 'MAT-001',
        materialName: '胶料A',
        quantity: 500,
        uom: 'kg',
        shift: '早班',
        priority: 'HIGH',
      },
      {
        id: 'WO-1002',
        name: 'WO-1002 - 胶料B',
        start: new Date(2024, 11, 25, 8, 30, 0).getTime(),
        end: new Date(2024, 11, 25, 10, 0, 0).getTime(),
        progress: 30,
        type: 'task' as const,
        dependencies: ['WO-1001'],
        invOrg: 'ORG-01',
        woCode: 'WO-1002',
        operation: 'OP-2',
        workCenter: '硫化缸01',
        materialCode: 'MAT-002',
        materialName: '胶料B',
        quantity: 300,
        uom: 'kg',
        shift: '早班',
        priority: 'MEDIUM',
      },
      {
        id: 'WO-1003',
        name: 'WO-1003 - 胶料C',
        start: new Date(2024, 11, 25, 11, 0, 0).getTime(),
        end: new Date(2024, 11, 25, 12, 30, 0).getTime(),
        progress: 20,
        type: 'task' as const,
        dependencies: ['WO-1002'],
        invOrg: 'ORG-01',
        woCode: 'WO-1003',
        operation: 'OP-3',
        workCenter: '硫化缸01',
        materialCode: 'MAT-003',
        materialName: '胶料C',
        quantity: 400,
        uom: 'kg',
        shift: '中班',
        priority: 'LOW',
      },
      {
        id: 'WO-1004',
        name: 'WO-1004 - 胶料D',
        start: new Date(2024, 11, 25, 14, 0, 0).getTime(),
        end: new Date(2024, 11, 25, 15, 30, 0).getTime(),
        progress: 15,
        type: 'task' as const,
        dependencies: ['WO-1003'],
        invOrg: 'ORG-01',
        woCode: 'WO-1004',
        operation: 'OP-4',
        workCenter: '硫化缸01',
        materialCode: 'MAT-004',
        materialName: '胶料D',
        quantity: 250,
        uom: 'kg',
        shift: '中班',
        priority: 'HIGH',
      },
      {
        id: 'WO-1005',
        name: 'WO-1005 - 胶料E',
        start: new Date(2024, 11, 25, 16, 30, 0).getTime(),
        end: new Date(2024, 11, 25, 18, 0, 0).getTime(),
        progress: 10,
        type: 'task' as const,
        dependencies: ['WO-1004'],
        invOrg: 'ORG-01',
        woCode: 'WO-1005',
        operation: 'OP-5',
        workCenter: '硫化缸01',
        materialCode: 'MAT-005',
        materialName: '胶料E',
        quantity: 350,
        uom: 'kg',
        shift: '中班',
        priority: 'MEDIUM',
      },
    ],
  },
  {
    id: '硫化缸02',
    name: '硫化缸02',
    progress: 0,
    type: 'task' as const,
    hideChildren: false,
    children: [
      {
        id: 'WO-2001',
        name: 'WO-2001 - 胶料F',
        start: new Date(2024, 11, 25, 6, 30, 0).getTime(),
        end: new Date(2024, 11, 25, 8, 0, 0).getTime(),
        progress: 40,
        type: 'task' as const,
        invOrg: 'ORG-01',
        woCode: 'WO-2001',
        operation: 'OP-1',
        workCenter: '硫化缸02',
        materialCode: 'MAT-006',
        materialName: '胶料F',
        quantity: 600,
        uom: 'kg',
        shift: '早班',
        priority: 'HIGH',
      },
      {
        id: 'WO-2002',
        name: 'WO-2002 - 胶料G',
        start: new Date(2024, 11, 25, 9, 0, 0).getTime(),
        end: new Date(2024, 11, 25, 10, 30, 0).getTime(),
        progress: 25,
        type: 'task' as const,
        dependencies: ['WO-2001'],
        invOrg: 'ORG-01',
        woCode: 'WO-2002',
        operation: 'OP-2',
        workCenter: '硫化缸02',
        materialCode: 'MAT-007',
        materialName: '胶料G',
        quantity: 400,
        uom: 'kg',
        shift: '早班',
        priority: 'MEDIUM',
      },
      {
        id: 'WO-2003',
        name: 'WO-2003 - 胶料H',
        start: new Date(2024, 11, 25, 11, 30, 0).getTime(),
        end: new Date(2024, 11, 25, 13, 0, 0).getTime(),
        progress: 15,
        type: 'task' as const,
        dependencies: ['WO-2002'],
        invOrg: 'ORG-01',
        woCode: 'WO-2003',
        operation: 'OP-3',
        workCenter: '硫化缸02',
        materialCode: 'MAT-008',
        materialName: '胶料H',
        quantity: 500,
        uom: 'kg',
        shift: '中班',
        priority: 'LOW',
      },
      {
        id: 'WO-2004',
        name: 'WO-2004 - 胶料I',
        start: new Date(2024, 11, 25, 14, 30, 0).getTime(),
        end: new Date(2024, 11, 25, 16, 0, 0).getTime(),
        progress: 10,
        type: 'task' as const,
        dependencies: ['WO-2003'],
        invOrg: 'ORG-01',
        woCode: 'WO-2004',
        operation: 'OP-4',
        workCenter: '硫化缸02',
        materialCode: 'MAT-009',
        materialName: '胶料I',
        quantity: 300,
        uom: 'kg',
        shift: '中班',
        priority: 'HIGH',
      },
      {
        id: 'WO-2005',
        name: 'WO-2005 - 胶料J',
        start: new Date(2024, 11, 25, 17, 0, 0).getTime(),
        end: new Date(2024, 11, 25, 18, 0, 0).getTime(),
        progress: 5,
        type: 'task' as const,
        dependencies: ['WO-2004'],
        invOrg: 'ORG-01',
        woCode: 'WO-2005',
        operation: 'OP-5',
        workCenter: '硫化缸02',
        materialCode: 'MAT-010',
        materialName: '胶料J',
        quantity: 450,
        uom: 'kg',
        shift: '中班',
        priority: 'MEDIUM',
      },
    ],
  },
  {
    id: '硫化缸03',
    name: '硫化缸03',
    progress: 0,
    type: 'task' as const,
    hideChildren: false,
    children: [
      {
        id: 'WO-3001',
        name: 'WO-3001 - 胶料K',
        start: new Date(2024, 11, 25, 6, 15, 0).getTime(),
        end: new Date(2024, 11, 25, 7, 45, 0).getTime(),
        progress: 35,
        type: 'task' as const,
        invOrg: 'ORG-01',
        woCode: 'WO-3001',
        operation: 'OP-1',
        workCenter: '硫化缸03',
        materialCode: 'MAT-011',
        materialName: '胶料K',
        quantity: 700,
        uom: 'kg',
        shift: '早班',
        priority: 'HIGH',
      },
      {
        id: 'WO-3002',
        name: 'WO-3002 - 胶料L',
        start: new Date(2024, 11, 25, 8, 45, 0).getTime(),
        end: new Date(2024, 11, 25, 10, 15, 0).getTime(),
        progress: 20,
        type: 'task' as const,
        dependencies: ['WO-3001'],
        invOrg: 'ORG-01',
        woCode: 'WO-3002',
        operation: 'OP-2',
        workCenter: '硫化缸03',
        materialCode: 'MAT-012',
        materialName: '胶料L',
        quantity: 500,
        uom: 'kg',
        shift: '早班',
        priority: 'MEDIUM',
      },
      {
        id: 'WO-3003',
        name: 'WO-3003 - 胶料M',
        start: new Date(2024, 11, 25, 11, 15, 0).getTime(),
        end: new Date(2024, 11, 25, 12, 45, 0).getTime(),
        progress: 10,
        type: 'task' as const,
        dependencies: ['WO-3002'],
        invOrg: 'ORG-01',
        woCode: 'WO-3003',
        operation: 'OP-3',
        workCenter: '硫化缸03',
        materialCode: 'MAT-013',
        materialName: '胶料M',
        quantity: 600,
        uom: 'kg',
        shift: '中班',
        priority: 'LOW',
      },
      {
        id: 'WO-3004',
        name: 'WO-3004 - 胶料N',
        start: new Date(2024, 11, 25, 13, 45, 0).getTime(),
        end: new Date(2024, 11, 25, 15, 15, 0).getTime(),
        progress: 5,
        type: 'task' as const,
        dependencies: ['WO-3003'],
        invOrg: 'ORG-01',
        woCode: 'WO-3004',
        operation: 'OP-4',
        workCenter: '硫化缸03',
        materialCode: 'MAT-014',
        materialName: '胶料N',
        quantity: 400,
        uom: 'kg',
        shift: '中班',
        priority: 'HIGH',
      },
      {
        id: 'WO-3005',
        name: 'WO-3005 - 胶料O',
        start: new Date(2024, 11, 25, 16, 15, 0).getTime(),
        end: new Date(2024, 11, 25, 18, 0, 0).getTime(),
        progress: 0,
        type: 'task' as const,
        dependencies: ['WO-3004'],
        invOrg: 'ORG-01',
        woCode: 'WO-3005',
        operation: 'OP-5',
        workCenter: '硫化缸03',
        materialCode: 'MAT-015',
        materialName: '胶料O',
        quantity: 550,
        uom: 'kg',
        shift: '中班',
        priority: 'MEDIUM',
      },
    ],
  },
  {
    id: '硫化缸04',
    name: '硫化缸04',
    progress: 0,
    type: 'task' as const,
    hideChildren: false,
    children: [
      {
        id: 'WO-4001',
        name: 'WO-4001 - 胶料P',
        start: new Date(2024, 11, 25, 6, 45, 0).getTime(),
        end: new Date(2024, 11, 25, 8, 15, 0).getTime(),
        progress: 30,
        type: 'task' as const,
        invOrg: 'ORG-01',
        woCode: 'WO-4001',
        operation: 'OP-1',
        workCenter: '硫化缸04',
        materialCode: 'MAT-016',
        materialName: '胶料P',
        quantity: 800,
        uom: 'kg',
        shift: '早班',
        priority: 'HIGH',
      },
      {
        id: 'WO-4002',
        name: 'WO-4002 - 胶料Q',
        start: new Date(2024, 11, 25, 9, 15, 0).getTime(),
        end: new Date(2024, 11, 25, 10, 45, 0).getTime(),
        progress: 15,
        type: 'task' as const,
        dependencies: ['WO-4001'],
        invOrg: 'ORG-01',
        woCode: 'WO-4002',
        operation: 'OP-2',
        workCenter: '硫化缸04',
        materialCode: 'MAT-017',
        materialName: '胶料Q',
        quantity: 600,
        uom: 'kg',
        shift: '早班',
        priority: 'MEDIUM',
      },
      {
        id: 'WO-4003',
        name: 'WO-4003 - 胶料R',
        start: new Date(2024, 11, 25, 11, 45, 0).getTime(),
        end: new Date(2024, 11, 25, 13, 15, 0).getTime(),
        progress: 8,
        type: 'task' as const,
        dependencies: ['WO-4002'],
        invOrg: 'ORG-01',
        woCode: 'WO-4003',
        operation: 'OP-3',
        workCenter: '硫化缸04',
        materialCode: 'MAT-018',
        materialName: '胶料R',
        quantity: 700,
        uom: 'kg',
        shift: '中班',
        priority: 'LOW',
      },
      {
        id: 'WO-4004',
        name: 'WO-4004 - 胶料S',
        start: new Date(2024, 11, 25, 14, 15, 0).getTime(),
        end: new Date(2024, 11, 25, 15, 45, 0).getTime(),
        progress: 3,
        type: 'task' as const,
        dependencies: ['WO-4003'],
        invOrg: 'ORG-01',
        woCode: 'WO-4004',
        operation: 'OP-4',
        workCenter: '硫化缸04',
        materialCode: 'MAT-019',
        materialName: '胶料S',
        quantity: 500,
        uom: 'kg',
        shift: '中班',
        priority: 'HIGH',
      },
      {
        id: 'WO-4005',
        name: 'WO-4005 - 胶料T',
        start: new Date(2024, 11, 25, 16, 45, 0).getTime(),
        end: new Date(2024, 11, 25, 18, 0, 0).getTime(),
        progress: 0,
        type: 'task' as const,
        dependencies: ['WO-4004'],
        invOrg: 'ORG-01',
        woCode: 'WO-4005',
        operation: 'OP-5',
        workCenter: '硫化缸04',
        materialCode: 'MAT-020',
        materialName: '胶料T',
        quantity: 650,
        uom: 'kg',
        shift: '中班',
        priority: 'MEDIUM',
      },
    ],
  },
  {
    id: '硫化缸05',
    name: '硫化缸05',
    progress: 0,
    type: 'task' as const,
    hideChildren: false,
    children: [
      {
        id: 'WO-5001',
        name: 'WO-5001 - 胶料U',
        start: new Date(2024, 11, 25, 6, 20, 0).getTime(),
        end: new Date(2024, 11, 25, 7, 50, 0).getTime(),
        progress: 25,
        type: 'task' as const,
        invOrg: 'ORG-01',
        woCode: 'WO-5001',
        operation: 'OP-1',
        workCenter: '硫化缸05',
        materialCode: 'MAT-021',
        materialName: '胶料U',
        quantity: 900,
        uom: 'kg',
        shift: '早班',
        priority: 'HIGH',
      },
      {
        id: 'WO-5002',
        name: 'WO-5002 - 胶料V',
        start: new Date(2024, 11, 25, 8, 50, 0).getTime(),
        end: new Date(2024, 11, 25, 10, 20, 0).getTime(),
        progress: 12,
        type: 'task' as const,
        dependencies: ['WO-5001'],
        invOrg: 'ORG-01',
        woCode: 'WO-5002',
        operation: 'OP-2',
        workCenter: '硫化缸05',
        materialCode: 'MAT-022',
        materialName: '胶料V',
        quantity: 700,
        uom: 'kg',
        shift: '早班',
        priority: 'MEDIUM',
      },
      {
        id: 'WO-5003',
        name: 'WO-5003 - 胶料W',
        start: new Date(2024, 11, 25, 11, 20, 0).getTime(),
        end: new Date(2024, 11, 25, 12, 50, 0).getTime(),
        progress: 8,
        type: 'task' as const,
        dependencies: ['WO-5002'],
        invOrg: 'ORG-01',
        woCode: 'WO-5003',
        operation: 'OP-3',
        workCenter: '硫化缸05',
        materialCode: 'MAT-023',
        materialName: '胶料W',
        quantity: 800,
        uom: 'kg',
        shift: '中班',
        priority: 'LOW',
      },
      {
        id: 'WO-5004',
        name: 'WO-5004 - 胶料X',
        start: new Date(2024, 11, 25, 13, 50, 0).getTime(),
        end: new Date(2024, 11, 25, 15, 20, 0).getTime(),
        progress: 5,
        type: 'task' as const,
        dependencies: ['WO-5003'],
        invOrg: 'ORG-01',
        woCode: 'WO-5004',
        operation: 'OP-4',
        workCenter: '硫化缸05',
        materialCode: 'MAT-024',
        materialName: '胶料X',
        quantity: 600,
        uom: 'kg',
        shift: '中班',
        priority: 'HIGH',
      },
    ],
  },
  // 继续创建硫化缸06-50，为了简洁，我只展示前5个，实际会创建完整的50个
  // 这里我会生成剩余的45个硫化缸
  ...Array.from({ length: 45 }, (_, index) => {
    const tankNum = index + 6;
    const baseHour = 6 + (index % 6); // 6-11小时作为基础时间
    const baseMinute = (index % 4) * 15; // 0, 15, 30, 45分钟偏移

    return {
      id: `硫化缸${tankNum.toString().padStart(2, '0')}`,
      name: `硫化缸${tankNum.toString().padStart(2, '0')}`,
      progress: 0,
      type: 'task' as const,
      hideChildren: false,
      children: [
        {
          id: `WO-${tankNum}001`,
          name: `WO-${tankNum}001 - 胶料${String.fromCharCode(65 + ((index * 5) % 26))}`,
          start: new Date(2024, 11, 25, baseHour, baseMinute, 0).getTime(),
          end: new Date(
            2024,
            11,
            25,
            baseHour + 1,
            baseMinute + 30,
            0
          ).getTime(),
          progress: Math.floor(Math.random() * 50) + 10,
          type: 'task' as const,
          invOrg: 'ORG-01',
          woCode: `WO-${tankNum}001`,
          operation: 'OP-1',
          workCenter: `硫化缸${tankNum.toString().padStart(2, '0')}`,
          materialCode: `MAT-${(index * 5 + 25).toString().padStart(3, '0')}`,
          materialName: `胶料${String.fromCharCode(65 + ((index * 5) % 26))}`,
          quantity: Math.floor(Math.random() * 500) + 300,
          uom: 'kg',
          shift: index % 2 === 0 ? '早班' : '中班',
          priority: ['HIGH', 'MEDIUM', 'LOW'][index % 3],
        },
        {
          id: `WO-${tankNum}002`,
          name: `WO-${tankNum}002 - 胶料${String.fromCharCode(66 + ((index * 5) % 26))}`,
          start: new Date(2024, 11, 25, baseHour + 2, baseMinute, 0).getTime(),
          end: new Date(
            2024,
            11,
            25,
            baseHour + 3,
            baseMinute + 30,
            0
          ).getTime(),
          progress: Math.floor(Math.random() * 40) + 5,
          type: 'task' as const,
          dependencies: [`WO-${tankNum}001`],
          invOrg: 'ORG-01',
          woCode: `WO-${tankNum}002`,
          operation: 'OP-2',
          workCenter: `硫化缸${tankNum.toString().padStart(2, '0')}`,
          materialCode: `MAT-${(index * 5 + 26).toString().padStart(3, '0')}`,
          materialName: `胶料${String.fromCharCode(66 + ((index * 5) % 26))}`,
          quantity: Math.floor(Math.random() * 400) + 250,
          uom: 'kg',
          shift: index % 2 === 0 ? '早班' : '中班',
          priority: ['HIGH', 'MEDIUM', 'LOW'][(index + 1) % 3],
        },
        {
          id: `WO-${tankNum}003`,
          name: `WO-${tankNum}003 - 胶料${String.fromCharCode(67 + ((index * 5) % 26))}`,
          start: new Date(2024, 11, 25, baseHour + 4, baseMinute, 0).getTime(),
          end: new Date(
            2024,
            11,
            25,
            baseHour + 5,
            baseMinute + 30,
            0
          ).getTime(),
          progress: Math.floor(Math.random() * 30) + 2,
          type: 'task' as const,
          dependencies: [`WO-${tankNum}002`],
          invOrg: 'ORG-01',
          woCode: `WO-${tankNum}003`,
          operation: 'OP-3',
          workCenter: `硫化缸${tankNum.toString().padStart(2, '0')}`,
          materialCode: `MAT-${(index * 5 + 27).toString().padStart(3, '0')}`,
          materialName: `胶料${String.fromCharCode(67 + ((index * 5) % 26))}`,
          quantity: Math.floor(Math.random() * 600) + 400,
          uom: 'kg',
          shift: index % 2 === 0 ? '中班' : '晚班',
          priority: ['HIGH', 'MEDIUM', 'LOW'][(index + 2) % 3],
        },
        {
          id: `WO-${tankNum}004`,
          name: `WO-${tankNum}004 - 胶料${String.fromCharCode(68 + ((index * 5) % 26))}`,
          start: new Date(2024, 11, 25, baseHour + 6, baseMinute, 0).getTime(),
          end: new Date(
            2024,
            11,
            25,
            baseHour + 7,
            baseMinute + 30,
            0
          ).getTime(),
          progress: Math.floor(Math.random() * 20) + 1,
          type: 'task' as const,
          dependencies: [`WO-${tankNum}003`],
          invOrg: 'ORG-01',
          woCode: `WO-${tankNum}004`,
          operation: 'OP-4',
          workCenter: `硫化缸${tankNum.toString().padStart(2, '0')}`,
          materialCode: `MAT-${(index * 5 + 28).toString().padStart(3, '0')}`,
          materialName: `胶料${String.fromCharCode(68 + ((index * 5) % 26))}`,
          quantity: Math.floor(Math.random() * 350) + 200,
          uom: 'kg',
          shift: index % 2 === 0 ? '中班' : '晚班',
          priority: ['HIGH', 'MEDIUM', 'LOW'][(index + 3) % 3],
        },
        // 第5个任务（部分缸有5个任务）
        ...(index % 3 !== 0
          ? [
              {
                id: `WO-${tankNum}005`,
                name: `WO-${tankNum}005 - 胶料${String.fromCharCode(69 + ((index * 5) % 26))}`,
                start: new Date(
                  2024,
                  11,
                  25,
                  baseHour + 8,
                  baseMinute,
                  0
                ).getTime(),
                end: new Date(
                  2024,
                  11,
                  25,
                  baseHour + 9,
                  baseMinute + 30,
                  0
                ).getTime(),
                progress: Math.floor(Math.random() * 15),
                type: 'task' as const,
                dependencies: [`WO-${tankNum}004`],
                invOrg: 'ORG-01',
                woCode: `WO-${tankNum}005`,
                operation: 'OP-5',
                workCenter: `硫化缸${tankNum.toString().padStart(2, '0')}`,
                materialCode: `MAT-${(index * 5 + 29).toString().padStart(3, '0')}`,
                materialName: `胶料${String.fromCharCode(69 + ((index * 5) % 26))}`,
                quantity: Math.floor(Math.random() * 450) + 300,
                uom: 'kg',
                shift: '晚班',
                priority: ['HIGH', 'MEDIUM', 'LOW'][(index + 4) % 3],
              },
            ]
          : []),
      ],
    };
  }),
];
const ProdSchedule = () => {
  const handleHierarchyChange = (
    movedTask: Task,
    newParentTask: Task | null,
    allTasks: Task[]
  ) => {
    storyDebug('onHierarchyChange', movedTask, newParentTask, allTasks);
    setTasks(allTasks);
    return true;
  };
  const [tasks, setTasks] = React.useState<Task[]>(TASKS as unknown as Task[]);
  return (
    <Gantt
      columns={[
        {
          key: 'name',
          title: '资源',
          width: '200px',
        },
      ]}
      tasks={tasks}
      calendarRange={[
        new Date(2024, 11, 25, 6, 0, 0).getTime(),
        new Date(2024, 11, 25, 18, 0, 0).getTime(),
      ]}
      // childrenField="tasks"
      viewMode={ViewMode.HalfHour}
      onDateChange={(changedTask, all) => {
        storyDebug('onDateChange', changedTask, all);
        setTasks(all);
      }}
      onHierarchyChange={handleHierarchyChange}
      ganttHeight={1000}
      rowHeight={38}
      locale="zh-CN"
    />
  );
};

export default ProdSchedule;
